apiVersion: v1
kind: Pod
metadata:
  #nombre de pod
  name: doscont
spec:
  #detalle de contenedores que tendra el pod
  containers:
    #nombre de contenedor
  - name: cont1
    #nombre de imagen docker a usar
    image: python:3.6-alpine
    command: ['sh','-c','echo cont1 > index.html && python -m http.server 8082'] 
    
    #nombre de contenedor
  - name: cont2
    #nombre de imagen docker a usar
    image: python:3.6-alpine
    command: ['sh','-c','echo cont1 > index.html && python -m http.server 8083']