apiVersion: apps/v1
kind: Deployment
#Datos de deployment metadata y labels
metadata:
  name: deployment-test
  labels:
    app: front
#Inicio datos de replicaSet
spec:
  #Cantidad de replicas de pods a utilizar 
  replicas: 3
  selector:
    #clave, valor de pods que seran asociado a replicaSet
    matchLabels:
      app: front
#Fin datos de replicaSet
#Inicio datos pod      
  template:
    metadata:
      labels:
        app: front
    #Datos de contenedores que tendra el pod      
    spec:
      containers:
      - name: nginx
        image: nginx:alpine        
#Fin datos pod
